# -*- coding: utf-8 -*-
"""Treball_ESPECTRO_alumne.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/py-IQCC/py-IQCC.github.io/blob/main/Treball_ESPECTRO_alumne.ipynb

# <font color='steelblue'>**SIMULACIÓ TEÒRICA D'ESPECTRES DE ROTACIÓ I ROTACIÓ-VIBRACIÓ DE MOLÈCULES DIATÒMIQUES**</font>

##<font color='steelblue'>Continguts</font>
A. Introducció
1. Energia
1. Regles de selecció
1. Intensitat

B. Procediment
1. Constants espectroscòpiques
1. Aproximació rotor rígid
1. Aproximació rotor no rígid
1. Aproximació harmònica i rotor rígid
1. Aproximació anharmònica i rotor no rígid
1. Càlcul de l'energia de dissociació

C. Qüestions
1. Constants espectroscòpiques
1. Espectres
*   Espectre de rotació pura (4 espectres)
*   Espectres roto-vibracionals (4 espectres)
1. Energia de dissociació

D. Annex

---

## <font color='steelblue'>**A. Introducció**
En la primera part del treball heu aproximat la funció que representa la superfície d'energia potencia (PES) a partir d'un polinomi de 4rt grau. Aquesta funció, tal com ja vàrem explicar, ens servirà per poder trobar les diferents constants espectroscòpiques que necessitem per tal de representar els espectres de rotació pura i rotació-vibració per a la vostra molècula. Els diferents espectres es modelaran fent servir diferents aproximacions explicades a classe de teoria.

### <font color='steelblue'>**1. Energia**
En el Tema 7 ja vàrem introduir que l'energia en un estat qualsevol ens vindrà donada per l'expressió:

\begin{equation}
\begin{split}
E_{\text{v},J,m_J}=U_k(R_e)+h\nu_e\left(\text{v}+\frac{1}{2}\right)+hB_eJ(J+1)-h\nu_e\chi_e\left(\text{v}+\frac{1}{2}\right)^2 \\ -h\alpha_eJ(J+1)\left(\text{v}+\frac{1}{2}\right)-h{D}_eJ^2(J+1)^2+hY_{00}
\end{split}\tag{1}
\end{equation}

a on $U_k(R_e)$ és l'energia de la molècula per l'estat electrònic $k$ (en el nostre cas, l'estat electrònic fonamental) a la distància d'equilibri (calculada a la primera part del treball) i $\text{v}$ i $J$ són els nombres quàntics vibracionals i rotacionals, que prenen els valors $\text{v}=0,1,2,\dots$ i $J=0,1,2,\dots$,
respectivament.

En aquesta expressió de l'energia hi trobem la part electrònica (Tema 9), com la rotacional (Tema 8a) i vibracional (Tema 8b) amb les corresponents correccions que s'han explicat al llarg del curs.

A partir de la teoria de pertorbacions es pot demostrar que les diferents constants espectroscòpiques es poden expressar en funció de les derivades de l'energia de segon, tercer i quart ordre avaluades a la distància d'equilibri, $U''(R_e)$, $U^{III}(R_e)$ i $U^{IV}(R_e)$. Aquestes derivades les podeu calcular fàcilment a partir de la funció (polinomi de 4rt grau) que heu trobat a la primera part del treball <font color='red'>**(vigileu amb les unitats)!**</font>

$$B_e = \frac{h}{8\pi^2 \mu R_e^2}$$

$$D_e = \frac{4 B_e^3}{\nu_e^2}$$

$$\nu_e=\frac{1}{2\pi}\sqrt{\frac{k}{\mu}} \qquad k=U^{II}(R_e) \qquad \mu=\frac{m_1m_2}{m_1+m_2}$$

$$\nu_e \chi_e = \frac{B_e^2 R_e^4}{4 h \nu_e^2} \left[ \frac{10 B_e R_e^2 [U^{III}(R_e)]^2}{3 h \nu_e^2} -U^{IV}(R_e) \right]$$

$$\alpha_e = -\frac{2 B_e^2}{\nu_e} \left[ \frac{2 B_e R_e^3 U^{III}(R_e)}{h \nu_e^2} +3 \right]$$

L'últim terme de l'energia, $hY_{00}$, és una constant que no depèn de cap nombre quàntic, pel que no cal que la tinguem en compte. Aquesta també es podria calcular a partir de les constants espectroscòpiques i derivades de l'energia potencial. En el nostre cas no la calcularem pas.

La idea principal d'aquest treball és simular un espectre de rotació pura, i un de vibració rotació. Per això procedirem tal com hem estat explicant a teoria. Un cop tenim l'expressió de l'energia, i a partir de les regles de selecció, trobarem la posició de les diferents senyals. Un cop tinguem la posició, i a partir de la població dels diferents nivells, així com la probabilitat de transició, podrem saber quina intensitat relativa (alçada) tindran les diferent transicions.

### <font color='steelblue'>**2. Regles de selecció**
Per tal de poder simular els diferents espectres haurem de determinar la posició de les diferents senyals (en les unitats que corresponguin), que com molt bé recordeu vénen donades per les diferents regles de selecció.

Rotació Pura:
$$ \Delta \text{v}=0\qquad\Delta J=\pm1\qquad\Delta M_J=0,\pm1 $$

Rotació-vibració:
$$ \Delta \text{v}=\pm1,(\pm2,\pm3,\dots)\qquad\Delta J=0\pm1\qquad\Delta M_J=0,\pm1 $$

$\Delta J=0$ dependrà de si es tracta de una molècula de capa oberta o capa tancada.

### <font color='steelblue'>**3. Intensitat**
**La intensitat de la línia** corresponent a una transició d'un estat $m$ a $n$

$$ I_{m\to n}\propto N_m|\mu_{mn}|^2 $$

és proporcional a la població del nivell de partida, $N_m$, i a la integral del moment dipolar de transició entre els nivells inicial i final, $μ_{mn}$.

Per una banda assumirem que la població dels diferents estats segueix una distribució de Boltzmann de manera que

$$
N_m\propto g_me^{\frac{-\varepsilon_m}{kT}}
$$

a on $g_m$ correspon a la degeneració del nivell energètic (recordeu que els nivells rotacionals tenen una degeneració de $2J+1$) i $\varepsilon_m$ és l'energia del nivell $m$, $T$ és la temperatura, $k$ la constant de Boltzmann.

Per a cada nivell ($\nu$,$J$) podrem calcular la població a partir de:

$$
p_{\,\text{v},J}=\frac{g_m\,e^{\frac{-\varepsilon_m}{kT}}}{\sum\limits_Jg_m\,e^{\frac{-\varepsilon}{kT}}}
$$


> # <font color='red'>⚠ Atenció!</font>
> <font color='red'>Recordeu que un nivell $m$ vindrà donat per una combinació de nombres quàntics $\text{v}$ i $J$ de l'estat electrònic fonamental $E_{\text{v},J,m_l}(R_e)$</font>


Per altra banda, en el curs hem determinat les regles de selecció per les diferents transicions amb els models de rotor rígid i oscil·lador harmònic. Només ens vàrem fixar en quines integrals del moment dipolar de transició s'anul·laven, però de fet, és pot deduir també el valor d'aquestes integrals per les transicions permeses. Així, en el cas de transicions entre nivells rotacionals (entre $J \leftrightarrow J +1$) la integral pren el següent valor (veure també Physical Chemistry, Atkins 7th Edition)

$$
|\mu_{J\leftrightarrow J+1}|^2∝\frac{J+1}{2J+1}
$$

i en cas de transicions entre nivells vibracionals (entre $\text{v} ↔ \text{v}+1$)

$$
|\mu_{\text{v}\leftrightarrow \text{v}+1}|^2∝(\text{v}+1)
$$

Quan les transicions involucren canvis en els nombres quàntics rotacionals i vibracionals (espectre de rotació-vibració), el moment dipolar de transició vindrà donat pel seu producte

$$
|\mu_{J\leftrightarrow J+1}|^2\cdot|\mu_{\text{v}\leftrightarrow \text{v}+1}|^2
$$

> # 🗒 Nota
> *Aquestes integrals son les responsable de que les línies P i R de l'espectre de rotació-vibració no tinguin la mateixa intensitat. Per exemple, la línia de la branca P corresponent a la transició rotacional 1 → 0 hauria de tenir la mateixa intensitat que la corresponent a la transició 1 → 2 de la branca R si només tinguéssim en compte la població de partida, ja que és el mateix. Tot i
això, la integral del moment dipolar de transició és més gran en el primer cas (que val 1, ja que J=0) que no pas en el segon (amb un valor de 2/3, a on J=1).*


Com que la intensitat absoluta de les línies depèn de les condicions experimentals i altres paràmetres difícils de calcular, en el nostre cas estem determinant **intensitats relatives**.

---
## <font color='steelblue'>**B. Procediment** (mirar a on comença el codi per executar)

### **1. Constants espectroscòpiques**


### **2. Energia de cada nivell $\text{v},J$**


### **3. Poblacions**


### **4. Transicions (senyals de l'epectre) i intensitat**

---
## <font color='steelblue'>**C. Qüestions**
A continuació teniu les qüestions que heu d'anar contestant al llarg del treball. No cal que seguiu la mateixa numeració, es tracta de que vagin sortint els diferents apartats.

Penseu que es tracta de un treball, per tant, tot i que no demanem una introducció, sí que el final del treball anterior ha de formar part d'aquest. És a dir, tot es basa en una molècula assignada (poseu-la, no la podem endevinar) i d'un ajust que heu fet en el treball de quàntica.

Per tal de que sigui més fàcil de seguir tot plegat, el polinomi que heu ajustat a la primera part poseu-lo en unitats d'energia atòmica (**Hartrees**) i distància en **Agnstroms**.

### <font color='steelblue'>**1. Constants espectroscòpiques**
Feu una taula amb els valors calculats de les diferents constants i compareu-los amb valors experimentals que trobeu a la bibliografia (podeu consultar la base de dades del NIST per trobar dades experimentals https://webbook.nist.gov/)

> En la discussió de la comparació de dades fer servir paràmetres quantitatius (error absolut i relatiu) per podeu analitzar la seva semblança.

> També recordeu que les dades del Nist són les experimentals i les que vosaltres calculeu són les teòriques.

### <font color='steelblue'>**2. Espectres**

A continuació calculareu l'espectre de rotació pura i els rotovibracional per a la vostra molècula amb i sense correccions. Cadascun d'ells els calculeu a dues temperatures diferents (que triareu vosaltres mateixos depenent de la molècula).

En total tindreu, per a dues temperatures diferents:

*   Espectre de rotació pura amb l'aproximació de rotor rígid
*   Espectre de rotació pura tenint en compte la distorsió centrífuga
*   Espectre roto-vibracional amb l'aproximació de rotor rígid i oscil·lador harmònic
*   Espectre roto-vibracional amb tenint en compte totes les aproximacions, distorsió centrífuga, anharmonicitat i acoblament roto-vibracional.List item

#### **<u>2.1 Espectres de rotació pura </u>**

A partir del codi python, i de les dades que us han donat a l'apartat anterior representeu els diferents espectres a **dues temperatures diferents** (que podeu escollir vosaltres mateixos per tal de que es vegin clares unes quantes transicions i prou diferència entre els dos espectres).
Heu de representar, per cada temperatura, l'espectre de rotació tenint en compte només l'**aproximació de rotor rígid**, i dos espectres afegint-hi la **correcció degut a la distosió centrífuga**.

Per tal de discutir els resultats us podeu basar en la discussió dels diferents conceptes:

*   Separació entre línies de l'espectre
*   Aparició o no del cap de banda, i on hauria d'apareixer (en algun cas, si augmenteu molt la J us apareixerà, altres només la podreu calcular)
*   Efecte de la temperatura en els espectres (posició, intensitat, separció entre línies)

#### **<u>2.2 Espectres roto-vibracionals (v=0)</u>**
A partir del codi python, i de les dades que us han donat a l'apartat 1, representeu l'espectre roto-vibracional a **dues temperatures** diferents (que igual que abans podeu escollir per tal de que es veginn clares ues quantes transicions i prou diferència entre les intensitats). Per a cada espectre heu de representar les **bandes PQR** (la banda Q si ve al cas). També per a cada temperatura haureu de representar l'espectre només tenint en compte l'**aproximació de rotor rígir i oscil·lador harmònic**, i dos espectres tenint en compte **totes les correccions (distorsió centrífuga, anharmonicitat i acoblament roto-vibracional)**.

En total, igual que abans tindreu 4 espectres diferents que us serviran per discutir els resultats fent servir els conceptes:

*   Aparició o no de la banda Q (i a quina freqüència ha d'apareixer)
*   Separació entre les línies
*   Simetria de les bandes P i Q
*   Cap de banda i càlcul de la J corresponent al cap de banda
*   Efecte de la temperatura

### <font color='steelblue'>**3. Energia de dissociació**
A partir de les constants vibracionals (freqüència de vibració i constant de
anharmonicitat), calculeu $\text{v}_{límit}$ (nivell a on la separació entre dues transicions vibracional esdevé zero), i a partir d'aquest, amb l'expressió de l'energia, l'**energia de dissociació** ($D_o$ i $D_e$). Compareu el valor amb la obtinguda a la primera part del treball, tenint en compte quin son els valors que es poden comparar directament (($D_o$ o $D_e$)).

## <font color='steelblue'>**D. Annex**
* Es tracta d'un treball, **no d'una col·lecció de gràfics**. Per tant si només hi ha gràfics sense una explicació sobre ells (tal com posa el guió del treball) no els tindré en compte.
* Per comparar les dades amb experimentals, no vol dir només mirar-les i dir
“s'assemblen”, ja hi ha una dada quantitativa que serveix per això, **es diu error relatiu!**
* Les taules han de tenir un **petit encapçalament**, i sobretot **UNITATS!!!**
* Quan vulgueu expressar un número amb notació científica és : $3.00\cdot10^{-10}$, no valen trets directament amb la $3.00E-10$. La millor manera és que a les unitats ja hi tingueu el $10^{-10}$ i en el cos de la taula només les xifres significatives.
* **NO CAL que poseu les taules dels espectres**, per això us demano el fitxer `.ipynb`. **NOMÉS necessito els espectres**.
* Les gràfiques (espectres) també porten un **peu de figura**.
* Afegiu també la **gràfica amb el polinomi** que vàreu obtenir en la primera part del treball (així ens estalvieu una mica de feina), **i la molècula**.

# <font color='steelblue'>**PROCEDIMENT**

Iniciem carregant constants i llibreries.
"""

import numpy as np
import math
import matplotlib.pyplot as plt

#En aquest primer apartat definim les constant que fareu servir en les diferents fórmules. Quedeu-vos amb el nom amb què les heu definides (les majúscules i minúscules son importants)

# Constant de Plank (en unitats internacionals)
h = ...

# Velocitat de la llum al buit (en unitats internacionals)
c1 = ...

# Constant de Boltzmann
kB = ...

# Nombre d'Avogadro
NA = ...

# Conversió au a J
Hartree = ...

# Conversió m a amgstroms
AtoM = ...

"""Introduim les dades de la molècula així com la informació que heu obringut del polinomi extrapolador de la part de Quàntica."""

# Masses atòmiques (en unitats internacionals)
m1 = ...
m2 = ...

#Escriu la fórmula de la massa reduïda ("Capítol 1: Python bàsic" per el format de com escriure l'equació)
mu = ...

# Coeficinets del polinomi de la corba de potencial ajustada (recorda que el polinomi té la forma f(x)=ax4+bx3+cx2+dx+e) - Feu servir l'ajust de Hartrees/Angstroms
a, b, c, d, e = ..., ..., ..., ..., ...

# Distància d’equilibri (Angstroms)
Re = ...

"""Ara cal definir la funció del potencial i les seves derivades en funció dels coeficients que hem definit abans. Definiu les derivades en funció de a, b, c i d i de la distància d'enllaç r."""

def U(r):
    return ...

def dU(r):
    return ...

def dU2(r):
    return ...

def dU3(r):
    return ...

def dU4(r):
    return ...

"""## <font color='steelblue'>**1. Constants espectroscòpiques**
Un cop definides les funcions del potencial, calculem les constants espectroscòpiques.
"""

#Definició del valor de les derivades en la distància d'enllaç (Re)

UII=dU2(Re)*Hartree*AtoM**2
UIII=dU3(Re)*Hartree*AtoM**3
UIV=dU4(Re)*Hartree*AtoM**4

#Definiu les fórmules que teniu a la introducció. Feu servir les constant que heu definit abans i les derivades que acabeu de definir. COMPTE!! Re està en Angstroms!!!

Be = ...

k_force = ...

nu_e = ...

nu_e_chi_e = ...

chi_e = ...

alpha_e = ...

De = ...

print(f"\033[1;4mCONSTANTS ESPECTROSCÒPIQUES:\033[0m")
print(f"Be = {Be:.2e} s⁻¹")
print(f"k = {k_force:.2e} J/m2")
print(f"nu_e = {nu_e:.2e} s⁻¹")
print(f"nu_e·chi_e = {nu_e_chi_e:.2e} s⁻¹")
print(f"chi_e = {chi_e:.2e} s⁻¹")
print(f"alpha_e = {alpha_e:.2e} s⁻¹")
print(f"De = {De:.2e} s⁻¹")

"""## <font color='steelblue'>**2. Aproximació rotor rígid**"""

#Definim la funció de l'energia del rotor rígid, que dependrà de J:
def Erot(J):
  return ...

#Definim la formula per a calcular les poblacions, que dependrà de J i T:
def pop(J, T):
    return ...

#I definim també la suma d'aquestes poblacions:
def suma_poblacions(T, J_max):
    return sum(pop(J, T) for J in range(J_max + 1))

#Calculem les intensitats de cada línia:
def espectre_rot(T, J_max):
    intensitats = []
    posicions = []
    Js = []

    Z = suma_poblacions(T, J_max)  # Sumatori de poblacions

    for J in range(J_max):
        p_J = pop(J, T) / Z

        #Fórmula del moment dipolar al quadrat
        mu2 = ...

        #Fórmula de la intensitat de la línia
        intensitat_relativa = ...

        #Calculem la diferència d'energia entre els nivells J+1 i J (passeu-la a cm-1)
        delta_E = ...

        Js.append(J)
        intensitats.append(intensitat_relativa)
        posicions.append(delta_E)

        print(f"ΔE({J}→{J+1}) = {delta_E:.2f} cm⁻¹ | I_rel = {intensitat_relativa:.2e}")

    return Js, intensitats, posicions

#Definim la Temperatura i J màxima

T=...
J_max = ...

print("\033[1;4mΔE(J→J+1) (cm⁻¹) | I_rel\033[0m")
Js, intensitats, posicions = espectre_rot(T, J_max)
print("\n")

# -----------------
# Gràfic
# -----------------
plt.figure(figsize=(10,5))
plt.vlines(posicions, 0, intensitats, color='blue')
plt.xlabel("Nombre d’ona (cm⁻¹)")
plt.ylabel("Intensitat relativa")
plt.title(f"Espectre de rotació pura (T = {T} K)")
plt.grid(True)
plt.show()

"""## <font color='steelblue'>**3. Aproximació rotor no rígid**"""

#Definim la funció de l'energia del rotor rígid i la distorció centrífuga, que dependrà de J:
def Erot(J):
    Erotrig = ...
    Edc = ...
    return Erotrig + Edc

#Definim la fórmula per a calcular les poblacions, que dependrà de J i T:
def pob(J, T):
    return ...

#I definim també la suma d'aquestes poblacions:
def suma_poblacions(T, J_max):
    return sum(pob(J, T) for J in range(J_max + 1))

#Calculem les intensitats de cada línia:
def espectre_rot(T, J_max):
    intensitats = []
    posicions = []
    Js = []

    Z = suma_poblacions(T, J_max)  # Sumatori de poblacions

    for J in range(J_max):
        p_J = pob(J, T) / Z

        #Fórmula del moment dipolar al quadrat
        mu2 = ...

        #Fórmula de la intensitat de la línia
        intensitat_relativa = ...

        #Calculem la diferència d'energia entre els nivells J+1 i J (passeu-la a cm-1)
        delta_E = ...

        Js.append(J)
        intensitats.append(intensitat_relativa)
        posicions.append(delta_E)

        print(f"ΔE({J}→{J+1}) = {delta_E:.2f} cm⁻¹ | I_rel = {intensitat_relativa:.2e}")

    return Js, intensitats, posicions

#Definim la Temperatura i J màxima

T=...
J_max = ...

print("\033[1;4mΔE(J→J+1) (cm⁻¹) | I_rel\033[0m")
Js, intensitats, posicions = espectre_rot(T, J_max)
print("\n")

# -----------------
# Gràfic
# -----------------
plt.figure(figsize=(10,5))
plt.vlines(posicions, 0, intensitats, color='blue')
plt.xlabel("Nombre d’ona (cm⁻¹)")
plt.ylabel("Intensitat relativa normalitzada")
plt.title(f"Espectre de rotació pura amb distorció centrífuga (T = {T} K)")
plt.grid(True)
plt.show()

"""## <font color='steelblue'>**4. Aproximació harmònica i rotor rígid**"""

#Definim la funció de l'energia (rotor rígid + oscil·lador harmònic), que dependrà de v i J:
def Erotvib(v,J):
    Erot = ...
    Evib = ...
    return Evib + Erot

#Definim la fórmula per a calcular les poblacions, que dependrà de v (degut al Erotvib), J i T:
def pob(v, J, T):
    return ...

#I definim també la suma d'aquestes poblacions:
def suma_poblacions(T, J_max,v=0):
    return sum(pob(v, J, T) for J in range(J_max + 1))

def espectre_rotvib(T, J_max):
    nu_P = []  # posicions branca P
    I_P = []   # intensitats branca P

    nu_R = []  # posicions branca R
    I_R = []   # intensitats branca R

    Z = suma_poblacions(T, J_max)

    for J in range(J_max + 1):
        # Població normalitzada del nivell inicial
        p_J = (2 * J + 1) * np.exp(- (Erotvib(0, J) - Erotvib(0,0)) / (kB * T))

        # Branca P: v=0, J → v=1, J-1
        if J >= 1:
            #Calculem la diferència d'energia entre els nivells J-1 i J (passeu-la a cm-1)
            delta_E_P = ...
            #Fórmula del moment dipolar al quadrat per la branca P
            mu2_P = ...
            #Fórmula de la intensitat de la línia
            intensitat_relativa_P = ...
            nu_P.append(delta_E_P)
            I_P.append(intensitat_relativa_P)

        # Branca R: v=0, J → v=1, J+1
        if J < J_max:
            #Calculem la diferència d'energia entre els nivells J+1 i J (passeu-la a cm-1)
            delta_E_R = ...
            #Fórmula del moment dipolar al quadrat per la branca R
            mu2_R = ...
            #Fórmula de la intensitat de la línia
            intensitat_relativa_R = ...
            nu_R.append(delta_E_R)
            I_R.append(intensitat_relativa_R)

    # Branca Q: v=0, J=0 → v=1, J=0
    # En el cas que no tingueu branca Q (tot i que haureu de definir les funcions, poseu I_Q=0, així no la printarà)

    #Calculem la diferència d'energia entre els nivells J i J (passeu-la a cm-1)
    delta_E_Q = ...
    #Fórmula del moment dipolar al quadrat per la branca Q
    mu2_Q = 1
    #Fórmula de la població per la branca Q
    p_J_Q = (2 * J + 1) * np.exp(- (Erotvib(1, 0) - Erotvib(0,0)) / (kB * T))
    nu_Q = ...
    #Fórmula de la intensitat de la línia
    I_Q = ...

    return nu_P, I_P, nu_Q, I_Q, nu_R, I_R

#Definim la Temperatura i J màxima

T=...
J_max = ...


nu_P, I_P, nu_Q, I_Q, nu_R, I_R = espectre_rotvib(T, J_max)

# -----------------
# Gràfic
# -----------------
plt.figure(figsize=(10,5))
plt.vlines(nu_P, 0, I_P, color='green', label='Branca P')
plt.vlines(nu_Q, 0, I_Q, color='gray', label='Branca Q')
plt.vlines(nu_R, 0, I_R, color='orange', label='Branca R')
plt.xlabel("Nombre d’ona (cm⁻¹)")
plt.ylabel("Intensitat relativa")
plt.title(f"Espectre de rotació-vibració (harmònic + rotor rígid) (T = {T} K)")
plt.legend()
plt.grid(True)
plt.show()

"""## <font color='steelblue'>**5. Aproximació anharmònica i rotor no rígid**"""

#Definim la funció de l'energia (rotor no rígid + anharmonicitat), que dependrà de v i J:
def Etotal(v, J):
    Erot = ...
    Evib = ...
    Acob = ...
    return Evib + Erot + Acob

#Definim la fórmula per a calcular les poblacions, que dependrà de v (degut al Erotvib), J i T:
def pob(v, J, T):
    return ...

# Intensitat relativa d'una transició (inclou moment de transició efectiu)
def intensitat_relativa(v_i, J_i, v_f, J_f, T):
    p = pob(v_i, J_i, T)
    mu2 = (J_i + 1) / (2 * J_i + 1)
    return p * mu2

# Calcular espectre complet per branques P, Q, R
def espectre_rotvib(T, J_max):
    nu_P, I_P = [], []
    nu_Q, I_Q = [], []
    nu_R, I_R = [], []

    Z = sum(pob(0, J, T) for J in range(J_max + 1))

    for J in range(J_max + 1):

      # Població normalitzada del nivell inicial
        p_J =  (2 * J + 1) * np.exp(- (Etotal(0, J) - Etotal(0,0)) / (kB * T))


        # Branca P: J → J-1
        if J >= 1:
            #Calculem la diferència d'energia entre els nivells J-1 i J (passeu-la a cm-1)
            delta_E_P = ...
            #Fórmula del moment dipolar al quadrat per la branca P
            mu2_P = ...
            #Fórmula de la intensitat de la línia
            intensitat_relativa_P = ...
            nu_P.append(delta_E_P)
            I_P.append(intensitat_relativa_P)

        # Branca R: J → J+1
        if J < J_max:
            #Calculem la diferència d'energia entre els nivells J+1 i J (passeu-la a cm-1)
            delta_E_R = ...
            #Fórmula del moment dipolar al quadrat per la branca R
            mu2_R = ...
            #Fórmula de la intensitat de la línia
            intensitat_relativa_R = ...
            nu_R.append(delta_E_R)
            I_R.append(intensitat_relativa_R)

    # Branca Q: J → J
    #Calculem la diferència d'energia entre els nivells J i J (passeu-la a cm-1)
    delta_E_Q = ...
    #Fórmula del moment dipolar al quadrat per la branca Q
    mu2_Q = ...
    p_J_Q=(2 * J + 1) * np.exp(- (Etotal(1, 0) - Etotal(0,0)) / (kB * T))
    nu_Q = ...
    #Fórmula de la intensitat de la línia
    I_Q = ...

    return nu_P, I_P, nu_Q, I_Q, nu_R, I_R

#Definim la Temperatura i J màxima

T=...
J_max = ...


nu_P, I_P, nu_Q, I_Q, nu_R, I_R = espectre_rotvib(T, J_max)

# -----------------
# Gràfic
# -----------------
plt.figure(figsize=(10,5))
plt.vlines(nu_P, 0, I_P, color='green', label='Branca P')
plt.vlines(nu_Q, 0, I_Q, color='gray', label='Branca Q')
plt.vlines(nu_R, 0, I_R, color='orange', label='Branca R')
plt.xlabel("Nombre d’ona (cm⁻¹)")
plt.ylabel("Intensitat relativa")
plt.title(f"Espectre de rotació-vibració (anharmònic + rotor no rígid) (T={T} K)")
plt.legend(loc='upper left')
plt.grid(True)
plt.show()

"""## <font color='steelblue'>**6. Càlcul de l'energia de dissociació**"""

def calcular_dissociacio(nu_e, chi_e):
    #Fórmula per calcular la v_limit
    v_lim = ...
    v_lim_round = math.ceil(v_lim) # Aquesta és la funció per arrodonir per dalt

    # Fórmula per calcular l'energia de dissociació (De)
    De = ...  #Unitats internacionals
    De_kJ= ... #kJ/mol

    # Fórmula per calcular D0
    D0 = ...  #Unitats internacionals
    D0_kJ= ... #kJ/mol

    return v_lim_round, De_kJ, D0_kJ

vlim, De, D0 = calcular_dissociacio(nu_e, chi_e)

# Resultats
print(f"v_limit = {vlim:.2f}")
print(f"D_e = {De:.2f} kJ/mol")
print(f"D_0 = {D0:.2f} kJ/mol")